# Generated by Django 4.2.2 on 2023-06-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsofproducts',
            old_name='category',
            new_name='categorysd',
        ),
    ]
