# Generated by Django 4.2.2 on 2023-06-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_category_groupsofproducts_categorysd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsofproducts',
            old_name='categorysd',
            new_name='category',
        ),
    ]
