# Generated by Django 4.2.2 on 2023-06-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_categoriesofproducts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsofproducts',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='group',
            new_name='group_id',
        ),
    ]
