# Generated by Django 4.2.2 on 2023-06-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_category_groupsofproducts_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsofproducts',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
