# Generated by Django 4.2.2 on 2023-06-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_groupsofproducts_id_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsofproducts',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoriesofproducts'),
        ),
        migrations.AlterField(
            model_name='products',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.groupsofproducts'),
        ),
    ]
